from config import DEFAULT_MODEL_DIR, DEFAULT_MODEL_NAME, DEFAULT_VSTORE_DIR, DEFAULT_VSTORE_NAME, DEFAULT_PDF_DIR

print(f"export DEFAULT_MODEL_DIR={DEFAULT_MODEL_DIR}")
print(f"export DEFAULT_MODEL_NAME={DEFAULT_MODEL_NAME}")
print(f"export DEFAULT_VSTORE_DIR={DEFAULT_VSTORE_DIR}")
print(f"export DEFAULT_VSTORE_NAME={DEFAULT_VSTORE_NAME}")
print(f"export DEFAULT_PDF_DIR={DEFAULT_PDF_DIR}")