#!/bin/bash

PYTHON=python3
SCRIPT_DIR=$(dirname $(readlink -f $BASH_SOURCE[0]))
SBIN_DIR=$(dirname $SCRIPT_DIR)
DEFAULT_PATH=$(dirname $SBIN_DIR)
CONFIG_SCRIPT=$DEFAULT_PATH/pylib/config/bashConfig.py

DEFAULT_MODEL_DIR=$($PYTHON $CONFIG_SCRIPT --DEFAULT_MODEL_DIR)
DEFAULT_MODEL_NAME=$($PYTHON $CONFIG_SCRIPT --DEFAULT_MODEL_NAME)
DEFAULT_VSTORE_DIR=$($PYTHON $CONFIG_SCRIPT --DEFAULT_VSTORE_DIR)
DEFAULT_VSTORE_NAME=$($PYTHON $CONFIG_SCRIPT --DEFAULT_VSTORE_NAME)
DEFAULT_PDF_DIR=$($PYTHON $CONFIG_SCRIPT --DEFAULT_PDF_DIR)
DEFAULT_RETRIEVE_NUM=$($PYTHON $CONFIG_SCRIPT --DEFAULT_RETRIEVE_NUM)
DEFAULT_SEARCH_OPTION=$($PYTHON $CONFIG_SCRIPT --DEFAULT_SEARCH_OPTION)