SCRIPT_DIR=$(dirname $(readlink -f $BASH_SOURCE[0]))
SBIN_DIR=$(dirname $SCRIPT_DIR)
DEFAULT_PATH=$(dirname $SBIN_DIR)
CONFIG_SCRIPT=$DEFAULT_PATH/pylib/config/bashConfig.py

DEFAULT_MODEL_DIR=$(python3 $CONFIG_SCRIPT --DEFAULT_MODEL_DIR)
DEFAULT_MODEL_NAME=$(python3 $CONFIG_SCRIPT --DEFAULT_MODEL_NAME)
DEFAULT_VSTORE_DIR=$(python3 $CONFIG_SCRIPT --DEFAULT_VSTORE_DIR)
DEFAULT_VSTORE_NAME=$(python3 $CONFIG_SCRIPT --DEFAULT_VSTORE_NAME)
DEFAULT_PDF_DIR=$(python3 $CONFIG_SCRIPT --DEFAULT_PDF_DIR)